<!--div class="questions" id="questions"-->
<?php if($lang=='es'){echo '<div class="questions hline">
<h1>Preguntas frecuentes hechas por nuestros clientes</h1>
	<p style="text-align:center;"><b>Hemos recopilado una gran cantidad de preguntas hechas por nuestros clientes con la finalidad de a que usted comprenda como podemos ajustar los programas de consejería de crédito de acuerdo a sus necesidades.</b></p>
		</br>
		<p><b>&#10149; ¿Es un programa de manejo de deudas lo mismo que un programa de arreglo de deudas?</b></br>No. En un programa de manejo de deudas usted va a pagar todas las deudas que usted debe pero en una forma que se adapte a su presupuesto – con un interés más bajo, de esta manera usted va a ahorrar dinero y pagar la deuda más rápidamente. En un programa de arreglo de deudas, como su nombre lo indica, se llega a un acuerdo con sus acreedores y pagará un saldo menor a lo adeudado a su acreedor pero la cuenta será cerrada y causará automáticamente una penalidad de 7 años  por cada arreglo de deuda la cual se verá reflejada en su reporte de crédito</p></br>
		<p><b>&#10149; ¿Es un programa de manejo de deudas lo mismo que un préstamo para consolidar deudas?</b></br>No, aunque un préstamo para consolidar deudas proporciona resultados similares a los que se obtiene con la consolidación de la deuda. En un programa de manejo de deudas, el equipo de consejeros de crédito negocia con sus acreedores una reducción en la tasa de interés que le cobran y el esquema mensual de pagos. Los pagos mensuales que realice a sus acreedores se regirán por este esquema de pagos.</br></br>Esto es diferente a un préstamo para consolidar deudas el cual usted puede obtener por su cuenta y que puede usar para pagar el saldo de sus tarjetas de crédito. Además puede ser algo difícil calificar para un préstamo personal.</br></br>Aunque las dos opciones consolidan las deudas en un sólo pago mensual con un interés reducido, existen diferencias entre ambos planes.</p></br>
		<p><b>&#10149; ¿Cómo la consolidación de deudas afecta mi crédito?</b></br>Esto depende de la opción que usó para consolidar las deudas y en lo exitoso que usted sea para ejecutar el plan. En la mayoría de los casos, la consolidación de deudas tendrá un efecto neutro o un efecto positivo en su crédito, a pesar de que usted use los servicios de consejería de crédito y se inscriba en un programa de manejo de deudas. Ya que el programa lo que busca es eliminar la deuda mientras construye un historial de pagos positivos, muchos usuarios han visto como su puntuación de crédito mejora al completar satisfactoriamente el programa.</p></br>
	
		<div class="closed">
			<p><b>&#10149; ¿Es este el mejor pago que me pueden ofrecer?</b></br>En la mayoría de los casos un programa de consejería de crédito le proveerá con el pago más bajo posible que usted puede conseguir al participar en un programa de consolidación de deudas. Durante su consulta confidencial, un consejero de crédito certificado evaluará su presupuesto y deudas para determinar el pago total mensual que razonablemente usted es capaz de hacer. Luego este esquema de pagos debe ser negociado y aceptado por sus acreedores. Todos los servicios de consejería de crédito a nivel nacional siguen estos lineamientos, por lo que su pago mensual será igual, sin importar cuál sea la agencia de consejería de crédito que usted use.</p></br>
			<p><b>&#10149; ¿Cómo se determina la tasa de interés?</b></br>El equipo de consejería de crédito se encarga de negociar con sus acreedores la posibilidad de reducir o eliminar la tasa de interés que le cobran en su programa personalizado de manejo de deudas. En promedio, las tasas de interés aplicadas a las deudas incluidas en el programa varían de un 0-11% además de que pueden variar dependiendo del cliente y los acreedores. Como resultado, usted obtiene un alivio de las deudas en el corto y largo plazo. Con menos interés usted obtiene la ventaja de pagar las deudas más rápidamente a pesar de que pague menos cada mes.</p></br>
		
			<p><b>&#10149; ¿El programa de manejo de deudas pagará todas mis tarjetas de crédito?</b></br>Las deudas de sus tarjetas de crédito serán canceladas en su totalidad al completar el programa satisfactoriamente, pero el servicio de consejería de crédito no pagará las deudas por usted. Usted tendrá que hacer sus pagos mensuales a Consolidated Credit, el dinero recibido será distribuido entre sus acreedores de acuerdo con el esquema de pagos negociados por los consejeros de crédito con sus acreedores. Como resultado, usted verá cómo los balances de sus cuentas irán disminuyendo gradualmente a medida que vaya haciendo sus pagos. Nótese que esto es un poco diferente a un préstamo para consolidar deudas. Con un préstamo para consolidar deudas, usted pide un préstamo y usa el dinero para pagar a sus acreedores en un solo pago total, dejando sólo el préstamo para ser pagado. Mientras que un programa de manejo de deudas se ajustan los pagos de acuerdo a un esquema planificado por usted y su consejero de crédito.</p></br>
			<p><b>&#10149; ¿Cuánto hay que pagar por el servicio de consolidación de deudas?</b></br>Hay un pequeño cargo que se hace por registrarse en el programa de manejo de deudas y otro cargo mensual muy bajo. Estos cargos se calculan de acuerdo a una fórmula que analiza su presupuesto y lo que usted puede pagar al mes. Todos los cargos se agregan a su pago mensual. Nótese que todos los cargos que se hacen por una agencia de consejería de crédito sin fines de lucro 501(c) 3 son regulados, por lo que no hay diferencia en los cargos que le cobra una agencia con respecto a otra.</p></br>
			<p><b>&#10149; ¿Puedo consolidar las deudas aun cuando estas han pasado a una agencia de cobranza de deudas?</b></br>Las deudas que ya se han pasado a una agencia de cobranza de deudas se pueden consolidar a través de un programa de manejo de deudas si la agencia lo aprueba. Parte del servicio de consejería de crédito es la de contactar a cada uno de los acreedores para negociar su participación en el programa. Los cobradores de deudas se incluyen en este proceso, entonces mientras que la agencia de cobranza lo acepte, entonces la consolidación de la deuda que está en una agencia de cobranza es absolutamente permitida.</p></br>
			<p><b>&#10149; ¿Mi cónyuge tiene que inscribirse en el programa conmigo?</b></br>Sólo se requiere que los cónyuges se inscriban en el programa de manejo de deudas si la deuda ha sido adquirida en conjunto. En otras palabras si usted firma en las cuentas conjuntamente con su cónyuge entonces debe incluirlas en el programa de manejo de deudas para lograr el máximo beneficio de alivio de deudas. No obstante, si uno de los cónyuges es sólo una firma autorizada o usuario de la cuenta y no tiene responsabilidad en las deudas, entonces no es necesario que se inscriba.</p></br>
			<p><b>&#10149; ¿Puedo hacer pagos extras para así poder cancelar la deuda más rápidamente?</b></br>Por supuesto, Nosotros lo recomendamos cada vez que le sea posible. Simplemente llame y hable con un representante de servicio al cliente, quien lo asistirá con el pago adicional que quiera hacer.</p></br>
			<p><b>&#10149; ¿Qué es una deuda con garantía?</b></br>Es aquella en la que el prestamista o acreedor requiere un colateral como garantía sobre la deuda. Las deudas aseguradas o con garantía no pueden ser incluidas en el programa de manejo de deudas o usar cualquier otro programa de consolidación de deudas. No obstante, las tarjetas de crédito con depósito o garantía si se pueden incluir en el programa.</p></br>
		</div>
		<div class="moreless"></div>
</div>';
}
else{echo '<div class="questions hline">
<h1>Frequently asked questions from our clients</h1>
	<p style="text-align:center;"><b>We’ve compiled the most asked questions from our clients to help you understand how we customize credit counseling programs for you.</b></p>
		</br>
		<p><b>&#10149; Is a debt management program the same as a debt settlement program?</b></br>No. With a debt management program, you pay off everything owed in a way that’s more manageable on a limited budget – at lower interest rates so you save money and still pay off debt fast. A debt settlement program settles debt for less than the full amount owed which closes that account and causes an automatic 7-year credit report penalty for every debt settled.</p></br>
		<p><b>&#10149; Is a debt management program the same as a personal debt consolidation loan?</b></br>No, although the program provides similar results to what you get with debt consolidation. The credit counseling team negotiates with your creditors to agree to an adjusted payment schedule at reduced interest rates. The monthly payments you make are disbursed between your creditors according to that schedule.</br>This is different from personal debt consolidation loans that you can take out on your own and use the money to pay off your credit cards.  It also may be more difficult to qualify for a personal loan. So while both options consolidate debt into one low-interest payment, they do so in slightly different ways.</p></br>
		<p><b>&#10149; How does debt consolidation affect my credit?</b></br>This depends on which option you use to consolidate debt and how successful you are at executing the plan. In most cases, the debt consolidation will have a neutral or positive affect on your credit, even if you use consumer credit counseling services to enroll in a debt management program. Since the program eliminates debt while helping you to build a positive payment history, many users see their credit scores increase upon successful completion of the program.</p></br>
	
		<div class="closed">
			<p><b>&#10149; Is this the lowest payment I can get?</b></br>In most cases as debt management program will provide the lowest payments you can achieve when you consolidate debt. During your confidential consultation, the certified credit counselor will evaluate your budget and debt to determine the total monthly payment you can reasonably afford to make.  Then the payment schedule would be negotiated and accepted by all of your creditors. All credit counseling service nationwide follow the same guidelines for the consolidation of debt, so the payment will be the same no matter which credit counseling services you end up using.</p></br>
			<p><b>&#10149; How is the interest rate determined?</b></br>The credit counseling team negotiates with your individual creditors to reduce or eliminate the interest rate applied to your customized debt management program. On average, interest rates on debts included in the program will range between 0-11%, although it may vary by client and creditor. As a result you get both short- and long-term debt relief. With less interest you eat up your monthly payments, you gain the advantage of paying off debt fast even though you pay less each month.</p></br>
		
			<p><b>&#10149; Does this credit counseling service pay off my credit cards?</b></br>Your credit cards will be paid off in-full upon program completion, but the credit counseling service itself does not pay off the debt for you. As you make the monthly payments to Consolidated Credit, the money received is disbursed amongst your creditors according to the schedule the credit counseling team negotiates with your creditors. As a result, you should see the balances on your accounts decrease gradually over time.</br>Note that this is a slightly different form of debt consolidation than other options like personal debt consolidation loans. With debt consolidation loans, you take out a loan and use the money to pay off your creditors in one lump sum, leaving only the loan to pay back. By contrast, this program simply adjusts your payment schedule.</p></br>
			<p><b>&#10149; What are your fees? / How much do you charge?</b></br>There is a small fee for setting you up on a debt management program, as well as a small monthly maintenance fee. These fees are calculated according to a formula that assesses your budget and what you can afford to pay. All fees are then rolled into your monthly payment amount so they are effectively included in your program payments. Note that fees for 501(c)3 nonprofit credit counseling services are regulated, so there’s typically no difference in the fees you’d pay using one service versus another.</p></br>
			<p><b>&#10149; Can I get a loan (mortgage/auto) while I’m enrolled?</b></br>Debts that have already passed to a third-party collection agency may be consolidated through a debt management program if the collector agrees. Part of the credit counseling services involves contacting each of your individual creditors to negotiate your enrollment in the program. Debt collectors are included in that process, so as long as the collector agrees then the consolidation of debt already in collections is absolutely permitted.</p></br>
			<p><b>&#10149; Does my spouse have to enroll in the program with me?</b></br>Spouses are only required to use credit counseling services and enroll together in a debt management program if the debts you wish to include in the program are held jointly. That means if you are cosigners on the accounts, then you must enroll together to get the maximum debt relief benefit. However, if one spouse is merely an authorized account user, then they would not be required to enroll. </p></br>
			<p><b>&#10149; Can I pay extra and pay off my credit card debt early?</b></br>Absolutely. We encourage it whenever possible.  Simply call to speak with a client services representative who can assist in applying the extra payment.</p></br>
			<p><b>&#10149; What does secured debt mean?</b></br>Secured debt refers to a situation where the money borrowed or credit line extended requires some type of collateral. Secured debts like a mortgage or auto loan cannot be consolidated on a debt management program or using any other type of debt consolidation. However, secured credit cards – where you put a cash deposit down to open the credit line – can be included on the program.</p></br>
		</div>
		<div class="moreless"></div>
</div>';
}
?>
